# Uncomment the following lines to enable the Glove80 RGB Underglow
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=n
CONFIG_EXPERIMENTAL_RGB_LAYER=y

# Uncomment to increase the transmit power of the keyboard's BLE radio.
# This will help if the connection to the host is bytes poor/teleports a lot.
# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Save power - enable deep sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
